### ISSUE TITLE
Can't login to GitLab

### ISSUE THREAD

**Issue by LightTemplar** [mgvora/gitplus_for_gitlab#2]
I can't login to my custom server, I get a following message from GitLab in browser;
`An error has occurred Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`

**Comment by godalming123** [comment]
What method did you use? Personal access tokens (PAT's)? If not they are recommended for these use cases because:
- you can revoke their access at any point
- you can set expire dates
- you can set custom permissions EG: git+ can read your repos but not write to them.
You can use a PAT by:
1. Go to https://gitlab.com/-/profile/personal_access_tokens
2. You should see personal access tokens
3. Now just scroll down and full in the form including:
- PAT name
- PAT expiration - optional
- PAT scopes - I would recommend enabling all of these
4. Click 'create personal access token'
5. Copy you PAT it should be under 'active personal access tokens' below the form.
6. Paste it into git+

**Comment by mgvora** [comment]
Personal access token implementation is available in the latest version on Google Play, I'm waiting for AppStore review, hope it will be within this week.

**Comment by LightTemplar** [comment]
With the last version I could get in, thanks! I tried basic authentitication and PATs - both variants work.
Before update I could only set my server adress and after clicking "login" I landed in browser into page with that error message.
